name: Build UnityAds

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Initialize submodule
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '8'

      - name: Install Ant
        run: |
          sudo apt-get update
          sudo apt-get install -y ant

      - name: Check App Inventor files
        run: |
          echo "=== .gitmodules ==="
          cat .gitmodules

          echo "=== lib/appinventor ==="
          ls -lah lib/appinventor

          echo "=== App Inventor JAR files ==="
          find lib/appinventor -maxdepth 1 -type f -name "*.jar" -print

      - name: Check dependencies
        run: |
          echo "=== lib/deps ==="
          ls -lah lib/deps

      - name: Build Extension
        run: ant extensions

      - name: Check AIX
        run: |
          echo "=== OUT ==="
          ls -lah out

      - name: Upload AIX
        uses: actions/upload-artifact@v4
        with:
          name: UnityAds-AIX
          path: out/*.aix
          if-no-files-found: error
